export interface Product {
  id: string;
  name: string;
  dosage: string;
  form: string;
  category: string;
  categoryId: string;
  description: string;
  researchAreas: string;
  storage: string;
  searchTags: string[]; // hidden tags for smart search
}

export interface Category {
  id: string;
  name: string;
  nameEn: string;
  description: string;
  descriptionEn: string;
}

export const categories: Category[] = [
  { id: "metabolic", name: "Метаболические / GLP-1 агонисты", nameEn: "Metabolic / GLP-1 Agonists", description: "Исследования метаболизма, аппетита, гликемии", descriptionEn: "Metabolism, appetite, glycemia research" },
  { id: "ghrh", name: "GHRH / GHRP / GH-axis", nameEn: "GHRH / GHRP / GH-axis", description: "Исследования гормона роста, секреции, регенерации", descriptionEn: "Growth hormone, secretion, regeneration research" },
  { id: "regeneration", name: "Регенерация и восстановление", nameEn: "Regeneration & Recovery", description: "Исследования заживления, воспаления, восстановления тканей", descriptionEn: "Healing, inflammation, tissue recovery research" },
  { id: "neuro", name: "Нейропептиды и нейрорегуляция", nameEn: "Neuropeptides & Neuroregulation", description: "Исследования когнитивных функций, нейропротекции, сна", descriptionEn: "Cognitive function, neuroprotection, sleep research" },
  { id: "mito", name: "Митохондриальные и энергетические исследования", nameEn: "Mitochondrial & Energy Research", description: "Исследования клеточной энергетики, митохондрий", descriptionEn: "Cellular energetics, mitochondria research" },
  { id: "muscle", name: "Мышечная регуляция и композиция тела", nameEn: "Muscle Regulation & Body Composition", description: "Исследования миостатина, мышечного роста", descriptionEn: "Myostatin, muscle growth research" },
  { id: "immune", name: "Иммунорегуляция", nameEn: "Immunoregulation", description: "Исследования иммунного ответа, воспаления, тимуса", descriptionEn: "Immune response, inflammation, thymus research" },
  { id: "derm", name: "Кожа, пигментация, дерматология", nameEn: "Skin, Pigmentation, Dermatology", description: "Исследования коллагена, меланогенеза", descriptionEn: "Collagen, melanogenesis research" },
  { id: "repro", name: "Репродуктивная и нейроэндокринная регуляция", nameEn: "Reproductive & Neuroendocrine Regulation", description: "Исследования гонадотропинов, либидо", descriptionEn: "Gonadotropin, libido research" },
  { id: "rare", name: "Редкие и экспериментальные молекулы", nameEn: "Rare & Experimental Molecules", description: "Экспериментальные соединения, ранние исследования", descriptionEn: "Experimental compounds, early research" },
  { id: "small", name: "Малые молекулы и исследовательские соединения", nameEn: "Small Molecules & Research Compounds", description: "Непептидные исследовательские соединения", descriptionEn: "Non-peptide research compounds" },
  { id: "solvents", name: "Растворители и лабораторные аксессуары", nameEn: "Solvents & Lab Accessories", description: "Бактериостатическая вода, расходные материалы", descriptionEn: "Bacteriostatic water, consumables" },
];

export const products: Product[] = [
  // ── Метаболические / GLP-1 ──
  { id: "semaglutide", name: "Semaglutide", dosage: "3 mg", form: "Lyophilized Powder", category: "Метаболические / GLP-1 агонисты", categoryId: "metabolic", description: "Агонист GLP-1R. Изучается в контексте метаболической регуляции, гликемии и инсулиновой чувствительности.", researchAreas: "Метаболизм, аппетит, гликемия, энергетический обмен", storage: "2–8°C", searchTags: ["semaglutide", "семаглутид", "ozempic", "оземпик", "wegovy", "вегови", "похудение", "аппетит", "диабет", "метаболизм", "glp-1", "глп-1", "вес", "weight loss", "appetite"] },
  { id: "tirzepatide", name: "Tirzepatide", dosage: "30 mg", form: "Lyophilized Powder", category: "Метаболические / GLP-1 агонисты", categoryId: "metabolic", description: "Двойной агонист GIP/GLP-1R. Изучается в контексте метаболической регуляции и липидного обмена.", researchAreas: "Метаболизм, аппетит, гликемия, липидный обмен", storage: "2–8°C", searchTags: ["tirzepatide", "тирзепатид", "mounjaro", "монжаро", "zepbound", "похудение", "аппетит", "диабет", "метаболизм", "gip", "glp-1", "вес"] },
  { id: "retatrutide-30", name: "Retatrutide", dosage: "30 mg", form: "Lyophilized Powder", category: "Метаболические / GLP-1 агонисты", categoryId: "metabolic", description: "Тройной агонист GLP-1/GIP/GCGR. Изучается в контексте энергетического обмена и метаболической регуляции.", researchAreas: "Метаболизм, энергетический обмен, гликемия", storage: "2–8°C", searchTags: ["retatrutide", "ретатрутид", "тройной агонист", "похудение", "метаболизм", "glp-1", "gip", "gcgr", "вес"] },
  { id: "retatrutide-15", name: "Retatrutide", dosage: "15 mg", form: "Lyophilized Powder", category: "Метаболические / GLP-1 агонисты", categoryId: "metabolic", description: "Тройной агонист GLP-1/GIP/GCGR. Дозировка для исследовательских протоколов.", researchAreas: "Метаболизм, энергетический обмен", storage: "2–8°C", searchTags: ["retatrutide", "ретатрутид", "тройной агонист", "похудение", "метаболизм"] },
  { id: "cagrisema", name: "CagriSema", dosage: "20 mg", form: "Lyophilized Powder", category: "Метаболические / GLP-1 агонисты", categoryId: "metabolic", description: "Комбинация GLP-1 + амилин. Изучается в контексте контроля аппетита и гликемии.", researchAreas: "Аппетит, гликемия, метаболизм", storage: "2–8°C", searchTags: ["cagrisema", "кагрисема", "cagrilintide", "semaglutide", "амилин", "похудение", "аппетит"] },
  { id: "mazdutide", name: "Mazdutide", dosage: "10 mg", form: "Lyophilized Powder", category: "Метаболические / GLP-1 агонисты", categoryId: "metabolic", description: "Двойной агонист GLP-1/GCGR. Изучается в контексте метаболической регуляции.", researchAreas: "Метаболизм, гликемия, липидный обмен", storage: "2–8°C", searchTags: ["mazdutide", "мазутид", "glp-1", "gcgr", "похудение", "метаболизм"] },
  { id: "survodutide", name: "Survodutide", dosage: "10 mg", form: "Lyophilized Powder", category: "Метаболические / GLP-1 агонисты", categoryId: "metabolic", description: "Двойной агонист GLP-1/GCGR. Изучается в контексте липидного обмена и метаболической регуляции.", researchAreas: "Липидный обмен, метаболизм", storage: "2–8°C", searchTags: ["survodutide", "сурводутид", "glp-1", "gcgr", "похудение", "метаболизм", "печень"] },
  { id: "aod9604", name: "AOD-9604", dosage: "10 mg", form: "Lyophilized Powder", category: "Метаболические / GLP-1 агонисты", categoryId: "metabolic", description: "Фрагмент GH (176-191). Изучается в контексте липолиза и жирового метаболизма.", researchAreas: "Липолиз, жировой метаболизм", storage: "2–8°C", searchTags: ["aod-9604", "aod9604", "fragment 176-191", "фрагмент", "жир", "липолиз", "похудение"] },
  { id: "tesofensine", name: "Tesofensine", dosage: "500 mcg", form: "Capsule", category: "Метаболические / GLP-1 агонисты", categoryId: "metabolic", description: "Ингибитор обратного захвата моноаминов. Изучается в контексте метаболической и нейрорегуляции.", researchAreas: "Метаболизм, нейрорегуляция, аппетит", storage: "Room temperature", searchTags: ["tesofensine", "тезофенсин", "моноамин", "похудение", "аппетит", "метаболизм"] },

  // ── GHRH / GHRP / GH-axis ──
  { id: "cjc1295-dac", name: "CJC-1295 DAC", dosage: "5 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Аналог GHRH с DAC. Изучается в контексте GH/IGF-1 axis и пролонгированной секреции GH.", researchAreas: "GH-axis, IGF-1, секреция гормона роста", storage: "2–8°C", searchTags: ["cjc-1295", "cjc1295", "dac", "ghrh", "гормон роста", "growth hormone", "igf-1", "восстановление", "сон", "sleep"] },
  { id: "cjc1295-nodac", name: "CJC-1295 No DAC", dosage: "5 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Mod GRF 1-29. Изучается в контексте пульсатильной секреции GH.", researchAreas: "GH-axis, пульсатильная секреция", storage: "2–8°C", searchTags: ["cjc-1295", "mod grf", "no dac", "гормон роста", "growth hormone", "igf-1", "восстановление"] },
  { id: "ipamorelin", name: "Ipamorelin", dosage: "5 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Селективный GHRP. Изучается в контексте GH-axis и восстановительных процессов.", researchAreas: "GH-axis, восстановление, секреция GH", storage: "2–8°C", searchTags: ["ipamorelin", "ипаморелин", "ghrp", "гормон роста", "growth hormone", "сон", "sleep", "восстановление"] },
  { id: "sermorelin", name: "Sermorelin", dosage: "5 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Аналог GHRH. Изучается в контексте физиологической стимуляции GH.", researchAreas: "GH-axis, секреция GH", storage: "2–8°C", searchTags: ["sermorelin", "серморелин", "ghrh", "гормон роста", "growth hormone", "восстановление", "сон"] },
  { id: "tesamorelin", name: "Tesamorelin", dosage: "10 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Аналог GHRH. Изучается в контексте GH-axis и липодистрофии.", researchAreas: "GH-axis, липодистрофия, секреция GH", storage: "2–8°C", searchTags: ["tesamorelin", "тесаморелин", "egrifta", "ghrh", "гормон роста", "жир", "липодистрофия"] },
  { id: "ghrp2", name: "GHRP-2", dosage: "5 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Секретагог GH. Изучается в контексте грелиновых рецепторов и GH-axis.", researchAreas: "GH-axis, грелин, секреция GH", storage: "2–8°C", searchTags: ["ghrp-2", "ghrp2", "грелин", "гормон роста", "growth hormone", "аппетит", "восстановление"] },
  { id: "ghrp6", name: "GHRP-6", dosage: "5 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Секретагог GH. Изучается в контексте GH-axis и стимуляции аппетита.", researchAreas: "GH-axis, аппетит, секреция GH", storage: "2–8°C", searchTags: ["ghrp-6", "ghrp6", "грелин", "гормон роста", "аппетит", "масса"] },
  { id: "hexarelin", name: "Hexarelin", dosage: "5 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Мощный GHRP. Изучается в контексте максимальной стимуляции GH.", researchAreas: "GH-axis, секреция GH", storage: "2–8°C", searchTags: ["hexarelin", "гексарелин", "ghrp", "гормон роста", "growth hormone"] },
  { id: "mk677", name: "MK-677 (Ibutamoren)", dosage: "25 mg", form: "Capsule", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Непептидный секретагог GH. Изучается в контексте GH/IGF-1 axis.", researchAreas: "GH-axis, IGF-1, секреция GH", storage: "Room temperature", searchTags: ["mk-677", "mk677", "ibutamoren", "ибутаморен", "гормон роста", "growth hormone", "сон", "sleep", "масса"] },
  { id: "fragment176", name: "Fragment 176-191", dosage: "5 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Фрагмент GH. Изучается в контексте липолиза без влияния на IGF-1.", researchAreas: "Липолиз, GH-axis", storage: "2–8°C", searchTags: ["fragment 176-191", "фрагмент", "hgh fragment", "жир", "липолиз", "похудение"] },
  { id: "igf1-lr3", name: "IGF-1 LR3", dosage: "1 mg", form: "Lyophilized Powder", category: "GHRH / GHRP / GH-axis", categoryId: "ghrh", description: "Аналог IGF-1 с увеличенным периодом полужизни. Изучается в контексте клеточной пролиферации.", researchAreas: "IGF-1 axis, клеточная пролиферация", storage: "2–8°C", searchTags: ["igf-1", "igf1 lr3", "инсулиноподобный фактор роста", "мышцы", "рост", "пролиферация"] },

  // ── Регенерация и восстановление ──
  { id: "bpc157", name: "BPC-157", dosage: "10 mg", form: "Lyophilized Powder", category: "Регенерация и восстановление", categoryId: "regeneration", description: "Пентадекапептид. Изучается в контексте тканевой регуляции, восстановления барьерных функций и воспалительных каскадов.", researchAreas: "Тканевая регуляция, барьерные функции, воспаление", storage: "2–8°C", searchTags: ["bpc-157", "bpc157", "бпц", "суставы", "кишечник", "заживление", "травма", "сухожилия", "связки", "joints", "gut", "healing", "регенерация"] },
  { id: "tb500", name: "TB-500", dosage: "5 mg", form: "Lyophilized Powder", category: "Регенерация и восстановление", categoryId: "regeneration", description: "Фрагмент Thymosin Beta-4. Изучается в контексте тканевой репарации и ангиогенеза.", researchAreas: "Тканевая репарация, ангиогенез, воспаление", storage: "2–8°C", searchTags: ["tb-500", "tb500", "thymosin beta-4", "тимозин", "заживление", "травма", "суставы", "восстановление", "healing"] },
  { id: "bpc-tb-blend", name: "BPC-157 + TB-500 Blend", dosage: "10 mg", form: "Lyophilized Powder", category: "Регенерация и восстановление", categoryId: "regeneration", description: "Комбинация BPC-157 и TB-500. Изучается в контексте синергии регенеративных каскадов.", researchAreas: "Регенерация, синергия, тканевая репарация", storage: "2–8°C", searchTags: ["bpc-157", "tb-500", "blend", "комбинация", "суставы", "заживление", "травма", "восстановление"] },
  { id: "ghk-cu", name: "GHK-Cu", dosage: "100 mg", form: "Lyophilized Powder", category: "Регенерация и восстановление", categoryId: "regeneration", description: "Медный трипептид. Изучается в контексте ремоделирования внеклеточного матрикса и регенерации.", researchAreas: "Внеклеточный матрикс, коллаген, регенерация", storage: "2–8°C", searchTags: ["ghk-cu", "ghk", "медный пептид", "copper peptide", "кожа", "коллаген", "волосы", "заживление", "skin", "collagen", "hair"] },
  { id: "kpv", name: "KPV", dosage: "5 mg", form: "Lyophilized Powder", category: "Регенерация и восстановление", categoryId: "regeneration", description: "Трипептид α-MSH. Изучается в контексте противовоспалительных каскадов и барьерных функций.", researchAreas: "Воспаление, барьерные функции, кишечник", storage: "2–8°C", searchTags: ["kpv", "alpha-msh", "воспаление", "кишечник", "барьер", "gut", "inflammation"] },
  { id: "ll37", name: "LL-37", dosage: "5 mg", form: "Lyophilized Powder", category: "Регенерация и восстановление", categoryId: "regeneration", description: "Антимикробный пептид. Изучается в контексте врождённого иммунитета и тканевой регуляции.", researchAreas: "Врождённый иммунитет, антимикробная активность", storage: "2–8°C", searchTags: ["ll-37", "ll37", "антимикробный", "иммунитет", "antimicrobial", "cathelicidin"] },
  { id: "thymosin-b4", name: "Thymosin Beta-4", dosage: "5 mg", form: "Lyophilized Powder", category: "Регенерация и восстановление", categoryId: "regeneration", description: "Полноразмерный тимозин бета-4. Изучается в контексте тканевой репарации и клеточной миграции.", researchAreas: "Тканевая репарация, клеточная миграция", storage: "2–8°C", searchTags: ["thymosin beta-4", "тимозин", "tb4", "заживление", "регенерация", "сердце", "heart"] },

  // ── Нейропептиды и нейрорегуляция ──
  { id: "selank", name: "Selank", dosage: "10 mg", form: "Lyophilized Powder", category: "Нейропептиды и нейрорегуляция", categoryId: "neuro", description: "Синтетический аналог тафтсина. Изучается в контексте нейрорегуляции, стресс-ответа и когнитивных процессов.", researchAreas: "Нейрорегуляция, стресс-ответ, когнитивные процессы", storage: "2–8°C", searchTags: ["selank", "селанк", "тревога", "стресс", "anxiety", "stress", "мозг", "brain", "когнитивный", "cognitive", "фокус"] },
  { id: "semax", name: "Semax Amidate", dosage: "30 mg", form: "Lyophilized Powder", category: "Нейропептиды и нейрорегуляция", categoryId: "neuro", description: "Аналог АКТГ(4-10). Изучается в контексте нейропротекции, BDNF и когнитивных процессов.", researchAreas: "Нейропротекция, BDNF, когнитивные процессы", storage: "2–8°C", searchTags: ["semax", "семакс", "amidate", "мозг", "brain", "память", "memory", "фокус", "focus", "bdnf", "нейропротекция"] },
  { id: "na-selank", name: "N-Acetyl Selank", dosage: "10 mg", form: "Lyophilized Powder", category: "Нейропептиды и нейрорегуляция", categoryId: "neuro", description: "Ацетилированная форма Selank. Повышенная стабильность. Изучается в контексте анксиолитических моделей.", researchAreas: "Анксиолитические модели, нейрорегуляция", storage: "2–8°C", searchTags: ["n-acetyl selank", "селанк", "тревога", "стресс", "anxiety", "нейро"] },
  { id: "na-semax", name: "N-Acetyl Semax", dosage: "30 mg", form: "Lyophilized Powder", category: "Нейропептиды и нейрорегуляция", categoryId: "neuro", description: "Ацетилированная форма Semax. Повышенная стабильность. Изучается в контексте нейропротекции.", researchAreas: "Нейропротекция, когнитивные процессы", storage: "2–8°C", searchTags: ["n-acetyl semax", "семакс", "мозг", "память", "bdnf", "нейропротекция"] },
  { id: "dsip", name: "DSIP", dosage: "5 mg", form: "Lyophilized Powder", category: "Нейропептиды и нейрорегуляция", categoryId: "neuro", description: "Delta Sleep-Inducing Peptide. Изучается в контексте регуляции сна и циркадных ритмов.", researchAreas: "Сон, циркадные ритмы, стресс", storage: "2–8°C", searchTags: ["dsip", "дсип", "сон", "sleep", "бессонница", "insomnia", "циркадный", "стресс"] },
  { id: "pinealon", name: "Pinealon", dosage: "20 mg", form: "Lyophilized Powder", category: "Нейропептиды и нейрорегуляция", categoryId: "neuro", description: "Трипептид пинеальной железы. Изучается в контексте нейрорегуляции и циркадных процессов.", researchAreas: "Пинеальная железа, нейрорегуляция", storage: "2–8°C", searchTags: ["pinealon", "пинеалон", "эпифиз", "сон", "sleep", "мелатонин", "циркадный"] },
  { id: "dihexa", name: "Dihexa", dosage: "50 mg", form: "Powder", category: "Нейропептиды и нейрорегуляция", categoryId: "neuro", description: "Производное ангиотензина IV. Изучается в контексте нейрогенеза и синаптической пластичности.", researchAreas: "Нейрогенез, синаптическая пластичность", storage: "2–8°C", searchTags: ["dihexa", "дигекса", "память", "memory", "нейрогенез", "мозг", "brain", "когнитивный"] },
  { id: "vip", name: "VIP", dosage: "5 mg", form: "Lyophilized Powder", category: "Нейропептиды и нейрорегуляция", categoryId: "neuro", description: "Вазоактивный интестинальный пептид. Изучается в контексте нейроэндокринной и иммунной регуляции.", researchAreas: "Нейроэндокринная регуляция, иммунная модуляция", storage: "2–8°C", searchTags: ["vip", "вип", "вазоактивный", "нейроэндокринный", "иммунитет", "воспаление"] },

  // ── Митохондриальные и энергетические исследования ──
  { id: "mots-c", name: "MOTS-c", dosage: "40 mg", form: "Lyophilized Powder", category: "Митохондриальные и энергетические исследования", categoryId: "mito", description: "Митохондриальный пептид. Изучается в контексте клеточной энергетики, AMPK-сигналинга и метаболической регуляции.", researchAreas: "Клеточная энергетика, AMPK, метаболизм", storage: "2–8°C", searchTags: ["mots-c", "motsc", "митохондрии", "энергия", "energy", "ampk", "метаболизм", "выносливость", "endurance", "старение", "aging"] },
  { id: "ss31", name: "SS-31 (Elamipretide)", dosage: "50 mg", form: "Lyophilized Powder", category: "Митохондриальные и энергетические исследования", categoryId: "mito", description: "Митохондриально-таргетный пептид. Изучается в контексте кардиолипинового ремоделирования и окислительного стресса.", researchAreas: "Митохондрии, кардиолипин, окислительный стресс", storage: "2–8°C", searchTags: ["ss-31", "ss31", "elamipretide", "элемипретид", "митохондрии", "энергия", "сердце", "heart", "старение"] },
  { id: "humanin", name: "Humanin", dosage: "5 mg", form: "Lyophilized Powder", category: "Митохондриальные и энергетические исследования", categoryId: "mito", description: "Митохондриальный пептид. Изучается в контексте цитопротекции и апоптоза.", researchAreas: "Цитопротекция, апоптоз, митохондрии", storage: "2–8°C", searchTags: ["humanin", "гуманин", "митохондрии", "апоптоз", "нейропротекция", "старение", "aging"] },

  // ── Мышечная регуляция ──
  { id: "ace031", name: "ACE-031", dosage: "1 mg", form: "Lyophilized Powder", category: "Мышечная регуляция и композиция тела", categoryId: "muscle", description: "Ловушка для миостатина/активина. Изучается в контексте мышечной регуляции и миостатинового пути.", researchAreas: "Миостатин, мышечная регуляция, композиция тела", storage: "2–8°C", searchTags: ["ace-031", "ace031", "миостатин", "myostatin", "мышцы", "muscles", "масса", "сила", "strength"] },
  { id: "follistatin", name: "Follistatin 344", dosage: "1 mg", form: "Lyophilized Powder", category: "Мышечная регуляция и композиция тела", categoryId: "muscle", description: "Ингибитор активина/миостатина. Изучается в контексте регуляции мышечной ткани.", researchAreas: "Миостатин, активин, мышечная ткань", storage: "2–8°C", searchTags: ["follistatin", "фоллистатин", "миостатин", "мышцы", "muscles", "масса", "рост мышц"] },
  { id: "peg-mgf", name: "PEG-MGF", dosage: "5 mg", form: "Lyophilized Powder", category: "Мышечная регуляция и композиция тела", categoryId: "muscle", description: "Пегилированный MGF. Изучается в контексте мышечной регенерации и IGF-1 axis.", researchAreas: "Мышечная регенерация, IGF-1 axis", storage: "2–8°C", searchTags: ["peg-mgf", "mgf", "мышцы", "muscles", "регенерация", "igf-1", "рост"] },
  { id: "mgf", name: "MGF", dosage: "5 mg", form: "Lyophilized Powder", category: "Мышечная регуляция и композиция тела", categoryId: "muscle", description: "Mechano Growth Factor. Изучается в контексте мышечной регенерации после повреждения.", researchAreas: "Мышечная регенерация, IGF-1", storage: "2–8°C", searchTags: ["mgf", "mechano growth factor", "мышцы", "muscles", "регенерация", "igf-1"] },

  // ── Иммунорегуляция ──
  { id: "thymosin-a1", name: "Thymosin Alpha-1", dosage: "5 mg", form: "Lyophilized Powder", category: "Иммунорегуляция", categoryId: "immune", description: "Пептид тимуса. Изучается в контексте T-клеточного ответа и цитокиновой модуляции.", researchAreas: "T-клеточный ответ, цитокины, иммунная модуляция", storage: "2–8°C", searchTags: ["thymosin alpha-1", "тимозин альфа", "иммунитет", "immunity", "т-клетки", "t-cells", "цитокины", "вирус"] },
  { id: "ara290", name: "ARA-290", dosage: "5 mg", form: "Lyophilized Powder", category: "Иммунорегуляция", categoryId: "immune", description: "Агонист рецептора EPO. Изучается в контексте нейропротекции и противовоспалительных каскадов.", researchAreas: "Нейропротекция, противовоспалительные каскады", storage: "2–8°C", searchTags: ["ara-290", "ara290", "epo", "нейропротекция", "воспаление", "inflammation", "нейропатия"] },

  // ── Кожа и пигментация ──
  { id: "melanotan2", name: "Melanotan II", dosage: "10 mg", form: "Lyophilized Powder", category: "Кожа, пигментация, дерматология", categoryId: "derm", description: "Аналог α-MSH. Изучается в контексте меланогенеза и рецепторных моделей MC1R.", researchAreas: "Меланогенез, MC1R, пигментация", storage: "2–8°C", searchTags: ["melanotan", "melanotan 2", "меланотан", "загар", "tan", "пигментация", "кожа", "skin", "mc1r"] },
  { id: "pt141", name: "PT-141 (Bremelanotide)", dosage: "10 mg", form: "Lyophilized Powder", category: "Кожа, пигментация, дерматология", categoryId: "derm", description: "Агонист MC рецепторов. Изучается в контексте нейроэндокринной регуляции и поведенческих моделей.", researchAreas: "MC рецепторы, нейроэндокринная регуляция", storage: "2–8°C", searchTags: ["pt-141", "pt141", "bremelanotide", "бремеланотид", "либидо", "libido", "mc рецепторы"] },

  // ── Репродуктивная регуляция ──
  { id: "kisspeptin", name: "Kisspeptin-10", dosage: "5 mg", form: "Lyophilized Powder", category: "Репродуктивная и нейроэндокринная регуляция", categoryId: "repro", description: "Нейропептид. Изучается в контексте GnRH-сигналинга и репродуктивной оси.", researchAreas: "GnRH-сигналинг, репродуктивная ось", storage: "2–8°C", searchTags: ["kisspeptin", "кисспептин", "gnrh", "репродукция", "reproduction", "фертильность", "fertility", "гонадотропин"] },
  { id: "gonadorelin", name: "Gonadorelin", dosage: "2 mg", form: "Lyophilized Powder", category: "Репродуктивная и нейроэндокринная регуляция", categoryId: "repro", description: "Аналог GnRH. Изучается в контексте гипоталамо-гипофизарно-гонадной оси.", researchAreas: "GnRH, гонадная ось, ЛГ/ФСГ", storage: "2–8°C", searchTags: ["gonadorelin", "гонадорелин", "gnrh", "лг", "фсг", "lh", "fsh", "тестостерон", "testosterone", "фертильность"] },
  { id: "oxytocin", name: "Oxytocin", dosage: "5 mg", form: "Lyophilized Powder", category: "Репродуктивная и нейроэндокринная регуляция", categoryId: "repro", description: "Нейропептид. Изучается в контексте нейроэндокринной регуляции и социальных поведенческих моделей.", researchAreas: "Нейроэндокринная регуляция, поведенческие модели", storage: "2–8°C", searchTags: ["oxytocin", "окситоцин", "социальное поведение", "нейроэндокринный", "доверие", "bonding"] },

  // ── Редкие и экспериментальные ──
  { id: "epitalon", name: "Epitalon", dosage: "10 mg", form: "Lyophilized Powder", category: "Редкие и экспериментальные молекулы", categoryId: "rare", description: "Тетрапептид. Изучается в контексте теломеразной активности и пинеальной регуляции.", researchAreas: "Теломераза, пинеальная регуляция, старение", storage: "2–8°C", searchTags: ["epitalon", "epithalon", "эпиталон", "теломераза", "telomerase", "старение", "aging", "долголетие", "longevity", "пинеальная железа"] },
  { id: "epithalon-40", name: "Epithalon", dosage: "40 mg", form: "Lyophilized Powder", category: "Редкие и экспериментальные молекулы", categoryId: "rare", description: "Тетрапептид. Увеличенная дозировка для расширенных исследовательских протоколов.", researchAreas: "Теломераза, пинеальная регуляция", storage: "2–8°C", searchTags: ["epithalon", "epitalon", "эпиталон", "теломераза", "старение", "aging", "долголетие"] },
  { id: "foxo4-dri", name: "FOXO4-DRI", dosage: "10 mg", form: "Lyophilized Powder", category: "Редкие и экспериментальные молекулы", categoryId: "rare", description: "Сенолитический пептид. Изучается в контексте клеточного старения и сенесцентных клеток.", researchAreas: "Сенолитика, клеточное старение", storage: "2–8°C", searchTags: ["foxo4-dri", "foxo4", "сенолитик", "senolytic", "старение", "aging", "сенесцентные клетки"] },
  { id: "p21", name: "P21", dosage: "50 mg", form: "Powder", category: "Редкие и экспериментальные молекулы", categoryId: "rare", description: "Пептидомиметик CNTF. Изучается в контексте нейрогенеза и когнитивных моделей.", researchAreas: "Нейрогенез, когнитивные модели", storage: "2–8°C", searchTags: ["p21", "cntf", "нейрогенез", "neurogenesis", "мозг", "brain", "память", "memory"] },

  // ── Малые молекулы ──
  { id: "5amino1mq-50", name: "5-Amino-1MQ", dosage: "50 mg", form: "Capsule", category: "Малые молекулы и исследовательские соединения", categoryId: "small", description: "Ингибитор NNMT. Изучается в контексте метаболических и клеточных моделей.", researchAreas: "NNMT, метаболизм, клеточные модели", storage: "Room temperature", searchTags: ["5-amino-1mq", "5amino1mq", "nnmt", "метаболизм", "жир", "fat", "энергия", "energy"] },
  { id: "5amino1mq-80", name: "5-Amino-1MQ", dosage: "80 mg", form: "Capsule", category: "Малые молекулы и исследовательские соединения", categoryId: "small", description: "Ингибитор NNMT. Увеличенная дозировка для расширенных протоколов.", researchAreas: "NNMT, метаболизм", storage: "Room temperature", searchTags: ["5-amino-1mq", "nnmt", "метаболизм", "жир", "энергия"] },
  { id: "noopept", name: "Noopept", dosage: "20 mg", form: "Capsule", category: "Малые молекулы и исследовательские соединения", categoryId: "small", description: "Дипептидный ноотроп. Изучается в контексте нейропротекции и когнитивных процессов.", researchAreas: "Нейропротекция, когнитивные процессы", storage: "Room temperature", searchTags: ["noopept", "ноопепт", "ноотроп", "nootropic", "память", "memory", "мозг", "brain", "фокус", "focus"] },
  { id: "bam15", name: "BAM-15", dosage: "50 mg", form: "Powder", category: "Малые молекулы и исследовательские соединения", categoryId: "small", description: "Митохондриальный разобщитель. Изучается в контексте клеточной энергетики и метаболизма.", researchAreas: "Митохондрии, клеточная энергетика, метаболизм", storage: "2–8°C", searchTags: ["bam-15", "bam15", "митохондрии", "разобщитель", "uncoupler", "энергия", "метаболизм"] },
  { id: "slu-pp-332", name: "SLU-PP-332", dosage: "50 mg", form: "Powder", category: "Малые молекулы и исследовательские соединения", categoryId: "small", description: "Агонист ERRα/γ. Изучается в контексте митохондриальной биогенеза и выносливости.", researchAreas: "ERR, митохондриальный биогенез, выносливость", storage: "2–8°C", searchTags: ["slu-pp-332", "err", "выносливость", "endurance", "митохондрии", "exercise"] },
  { id: "aicar", name: "AICAR", dosage: "50 mg", form: "Powder", category: "Малые молекулы и исследовательские соединения", categoryId: "small", description: "Активатор AMPK. Изучается в контексте клеточной энергетики и метаболической регуляции.", researchAreas: "AMPK, клеточная энергетика", storage: "2–8°C", searchTags: ["aicar", "аикар", "ampk", "энергия", "выносливость", "endurance", "метаболизм"] },
  { id: "methylene-blue", name: "Methylene Blue", dosage: "100 mg", form: "Solution", category: "Малые молекулы и исследовательские соединения", categoryId: "small", description: "Редокс-агент. Изучается в контексте митохондриальной функции и нейропротекции.", researchAreas: "Митохондрии, нейропротекция, редокс", storage: "Room temperature", searchTags: ["methylene blue", "метиленовый синий", "митохондрии", "нейропротекция", "редокс", "мозг"] },

  // ── Растворители и аксессуары ──
  { id: "bac-water", name: "Bacteriostatic Water", dosage: "10 ml", form: "Solution", category: "Растворители и лабораторные аксессуары", categoryId: "solvents", description: "Стерильная вода с 0.9% бензиловым спиртом для разведения лиофилизированных препаратов.", researchAreas: "Разведение, хранение, лабораторная работа", storage: "Room temperature", searchTags: ["bacteriostatic water", "бактериостатическая вода", "вода", "water", "разведение", "растворитель", "solvent"] },
  { id: "sterile-water", name: "Sterile Water", dosage: "10 ml", form: "Solution", category: "Растворители и лабораторные аксессуары", categoryId: "solvents", description: "Стерильная вода для инъекций. Разведение исследовательских препаратов.", researchAreas: "Разведение, лабораторная работа", storage: "Room temperature", searchTags: ["sterile water", "стерильная вода", "вода", "water", "разведение"] },
  { id: "nacl", name: "Sodium Chloride 0.9%", dosage: "10 ml", form: "Solution", category: "Растворители и лабораторные аксессуары", categoryId: "solvents", description: "Изотонический раствор NaCl для разведения и хранения пептидов.", researchAreas: "Разведение, хранение", storage: "Room temperature", searchTags: ["sodium chloride", "nacl", "физраствор", "saline", "хлорид натрия", "разведение"] },
];
